### ISSUE TITLE
DateTimeHelper problem with drafts

### ISSUE THREAD

**Issue by zauni** [craftcms/cms#7443]
### Description

Hello Craft Team,
after updating our Site from 3.5.17.1 to 3.6 there is a problem with drafts and live-preview/share-btn.

### Steps to reproduce

1. Create a new entry and click the "Share button" or try to open live preview

### Additional info

- Craft version: 3.6.0
- PHP version: 7.4.10
- Database driver & version: MySQL 5.7.31
- Plugins & versions: Redactor 2.8.5

Stack trace:

```
[-][1][-][error][ArgumentCountError] ArgumentCountError: Too few arguments to function craft\helpers\DateTimeHelper::toDateTime(), 0 passed in /var/www/html/vendor/craftcms/cms/src/validators/DateTimeValidator.php on line 81 and at least 1 expected in /var/www/html/vendor/craftcms/cms/src/helpers/DateTimeHelper.php:83
Stack trace:
#0 /var/www/html/vendor/craftcms/cms/src/validators/DateTimeValidator.php(81): craft\helpers\DateTimeHelper::toDateTime()
#1 /var/www/html/vendor/yiisoft/yii2/validators/Validator.php(261): craft\validators\DateTimeValidator->validateAttribute(Object(craft\records\Token), 'expiryDate')
#2 /var/www/html/vendor/yiisoft/yii2/base/Model.php(368): yii\validators\Validator->validateAttributes(Object(craft\records\Token), Array)
#3 /var/www/html/vendor/yiisoft/yii2/db/ActiveRecord.php(560): yii\base\Model->validate(Array)
#4 /var/www/html/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL)
#5 /var/www/html/vendor/craftcms/cms/src/services/Tokens.php(77): yii\db\BaseActiveRecord->save()
#6 /var/www/html/vendor/craftcms/cms/src/controllers/PreviewController.php(80): craft\services\Tokens->createToken(Array)
#7 [internal function]: craft\controllers\PreviewController->actionCreateToken()
#8 /var/www/html/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#9 /var/www/html/vendor/yiisoft/yii2/base/Controller.php(181): yii\base\InlineAction->runWithParams(Array)
#10 /var/www/html/vendor/craftcms/cms/src/web/Controller.php(190): yii\base\Controller->runAction('create-token', Array)
#11 /var/www/html/vendor/yiisoft/yii2/base/Module.php(534): craft\web\Controller->runAction('create-token', Array)
#12 /var/www/html/vendor/craftcms/cms/src/web/Application.php(274): yii\base\Module->runAction('preview/create-...', Array)
#13 /var/www/html/vendor/craftcms/cms/src/web/Application.php(577): craft\web\Application->runAction('preview/create-...', Array)
#14 /var/www/html/vendor/craftcms/cms/src/web/Application.php(253): craft\web\Application->_processActionRequest(Object(craft\web\Request))
#15 /var/www/html/vendor/yiisoft/yii2/base/Application.php(392): craft\web\Application->handleRequest(Object(craft\web\Request))
#16 /var/www/html/web/index.php(23): yii\base\Application->run()
#17 {main}
```

**Comment by brandonkelly** [comment]
This has already been fixed in 3.6.0.1 – thanks for reporting!

**Comment by zauni** [comment]
Okay that was the fast 👍 Thanks for the info.
