### ISSUE TITLE
[6.x]: Dashboard layout is broken after updating to 6.0.0-alpha.14 when a plugin requiring yii2-adapter is enabled

### ISSUE THREAD

**Issue by vnali** [craftcms/cms#19298]
### Description
My plugin, craft-counter requires yii2-adapter. After updating Craft to 6.0.0-alpha.14 and enabling my plugin, the dashboard throws console errors on widget load and dashboard layout is broken.

Errors seen:
```
Uncaught TypeError: can't access property "push", Craft.registeredJsFiles is undefined
Uncaught TypeError: Craft.getCookie is not a function
```

### Steps to reproduce

- Install fresh Craft 6.0.0-alpha.14. dashboard works fine.
- Enable counter plugin which require yii2-adapter.
- Load the control panel dashboard. Dashboard layout is broken. Open dev tools console.
- Observe the two errors above.
- Load a front-end page that registers the plugin's asset bundle.
 - Confirm the asset bundle is not registered/loaded, with no console error.

### Craft CMS version

6.0.0-alpha.14

### Installed plugins and versions

- [vnali/craft-counter
](https://github.com/vnali/craft-counter)

**Comment by brandonkelly** [comment]
Thanks for reporting that! Craft 6.0.0-alpha.15 is out with a fix.
